version: '3'

services:
  nginx:
    build:  
      context: ./nginx
    container_name: nginx
    image: killertiger/nginx:prod
    networks:
      - node-network
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: ./node
    container_name: app
    image: killertiger/app:prod
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - node-network
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    volumes:
      - ./mysql/database:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
